---
title: "Assignment 3"
author: "Jacob Jameson"
date: "Due Feb 27"
output: pdf_document
---


1. Construct this decision-analytic model in TreeAge (or another software package) using the information provided in the paper.



```{r, message=F, warning=F}
library(expm)
library(markovchain)
library(diagram)
library(pracma)

stateNames <- c("PC","Major Complication",
                "Minor Complication", "No Complication", 'Death')

model <- matrix(c(0, 0.10, 0.20, 0.67, 0.03,
                 0, 0.5, 0, 0, 0.5,
                 0, 0, 0.8, 0, 0.2,
                 0, 0, 0, 0.9, 0.1,
                 0, 0, 0, 0, 1), nrow=5, byrow  =TRUE)

row.names(model) <- stateNames; colnames(model) <- stateNames
model

plotmat(model, pos = c(1,3,1), 
        lwd = 1, box.lwd = 2, 
        cex.txt = 0.8, 
        box.size = 0.1, 
        box.type = "circle", 
        box.prop = 0.5,
        box.col = "light yellow",
        arr.length=.1,
        arr.width=.1,
        self.cex = .4,
        self.shifty = -.01,
        self.shiftx = .13,
        main = "")

```




2. Calculate the life expectancy for each strategy for at least one of the age/gender groups. Note: for background mortality, use the 2018 US life tables. These are published by the National Center for Health Statistics:

- Go to https://www.cdc.gov/nchs/products/life_tables.html

- Click on the pdf link for the "United States Life Tables, 2020" (NVSR Volume 71,
Number 1)

- On pages 17 and 19 in this document (Tables 2 and 3, top of page) there are links to download 2020 life tables for men and women respectively.

- In these spreadsheets, the first column (qx) provides annual mortality probabilities.


3. Compare your results with those shown in Table 3 of the paper, and discuss potential
reasons for any discrepancies (besides the different life tables).


4. Perform one-way sensitivity analysis on 2 of the key variables.


